# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151022233823 on 2015-10-24 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseTable',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('topic', models.CharField(blank=True, default=b'', max_length=255)),
                ('name', models.CharField(blank=True, default=b'', max_length=255)),
                ('cpc', models.CharField(blank=True, default=b'', max_length=255)),
                ('type', models.CharField(choices=[(b'L', b'Long'), (b'S', b'Short')], max_length=6)),
                ('age', models.CharField(blank=True, default=b'', max_length=2)),
                ('gender', models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female'), (b'E', b'Either')], max_length=6)),
                ('rating', models.CharField(blank=True, default=b'', max_length=2)),
                ('r1', models.CharField(blank=True, default=b'', max_length=255)),
                ('r2', models.CharField(blank=True, default=b'', max_length=255)),
                ('r3', models.CharField(blank=True, default=b'', max_length=255)),
                ('r4', models.CharField(blank=True, default=b'', max_length=255)),
                ('r5', models.CharField(blank=True, default=b'', max_length=255)),
                ('r6', models.CharField(blank=True, default=b'', max_length=255)),
                ('w1', models.CharField(blank=True, default=b'', max_length=255)),
                ('w2', models.CharField(blank=True, default=b'', max_length=255)),
                ('w3', models.CharField(blank=True, default=b'', max_length=255)),
                ('w4', models.CharField(blank=True, default=b'', max_length=255)),
                ('w5', models.CharField(blank=True, default=b'', max_length=255)),
                ('w6', models.CharField(blank=True, default=b'', max_length=255)),
                ('ab_status', models.CharField(choices=[(b'Y', b'Yes'), (b'N', b'No')], max_length=3)),
                ('role_player', models.BooleanField(default=False)),
                ('observer', models.BooleanField(default=False)),
                ('actor', models.BooleanField(default=False)),
                ('duration', models.CharField(blank=True, default=b'', max_length=255)),
            ],
        ),
    ]
