# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151022233823 on 2015-10-24 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminerTable',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, default=b'', max_length=255)),
                ('lastname', models.CharField(blank=True, default=b'', max_length=255)),
                ('gender', models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female'), (b'E', b'Either')], max_length=6)),
                ('state_province', models.CharField(blank=True, default=b'', max_length=20)),
                ('birthdate', models.CharField(blank=True, default=b'', max_length=20)),
                ('availability', models.CharField(choices=[(b'A', b'AM'), (b'P', b'PM'), (b'B', b'AM PM')], max_length=6)),
                ('aboriginal_status', models.CharField(choices=[(b'Y', b'Yes'), (b'N', b'No')], max_length=3)),
            ],
        ),
    ]
