# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151022233823 on 2015-10-24 05:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default_app', '0004_candidatetable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examinertable',
            old_name='aboriginal_status',
            new_name='ab_status',
        ),
    ]
